spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secure_programming?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Australia/Adelaide
    username: secprog_migrate
    password: 1qaz!QAZ
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mappers/UserInfoMapper.xml
  type-aliases-package: edu.adelaide.entity

server:
  port: 8080

logging:
  level:
    edu.adelaide.mapper: debug
